name: Deployment Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
 simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn --frozen-lockfile
      - run: yarn test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      - uses: SamKirkland/FTP-Deploy-Action@da0d77ff390a13097c60f9b9eb954e503a480d97
        if: ${{ github.event_name == 'push' }}
        with:
          ftp-server: sftp://ftp.199.188.200.186:21098/bloggr.xyz
          ftp-username: erwioqoa
          ftp-password: ${{ secrets.ftp_password }}
          git-ftp-args: --insecure
